# fly.toml app configuration file generated for fly-deployment-test-young-bush-9595 on 2023-12-14T23:06:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-deployment-test"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
